### ISSUE TITLE
springboot 合并部署,合并的一个模块springboot的依赖必须是provided吗

### ISSUE THREAD

**Issue by zhanghongbin** [sofastack-guides/spring-boot-ark-biz#10]
declaredMode 是什么意思，ark container 是一个springboot的程序，还有一个也是springboot的程序，我想把他们合并部署，生成ark biz ，为什么这个程序里边的springboot 依赖必须是protected的？例如  <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <scope>provided</scope>
        </dependency>

**Comment by it-linnan** [comment]
我也遇到了这个问题，在动态部署的场景下，install的biz是一个springboot项目，如果这个项目依赖了spring的包，install就会失败，并且不输出任何日志。

PS：biz与master biz的spring版本相同

以下是通过debug获取到的异常堆栈：
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:286)
	at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:172)
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:348)
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:333)
	at com.alipay.sofa.ark.container.service.biz.BizCommandProvider$BizCommand$1.run(BizCommandProvider.java:249)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:252)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:265)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325)
	at com.test.TestApplication.main(TestApplication.java:12)
	... 13 more
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: Post find class org.springframework.core.metrics.ApplicationStartup occurs an error via biz ClassLoaderHook: com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook@675a9e99.
Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook.postFindClass(DelegateToMasterBizClassLoaderHook.java:53)
	at com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook.postFindClass(DelegateToMasterBizClassLoaderHook.java:36)
	at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.postLoadClass(BizClassLoader.java:205)
	at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.loadClassInternal(BizClassLoader.java:127)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.lambda$loadClassWithCache$0(AbstractClasspathClassLoader.java:206)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClassWithCache(AbstractClasspathClassLoader.java:203)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:110)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:252)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:265)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325)
	at com.test.TestApplication.main(TestApplication.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:286)
	at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:172)
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:348)
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:333)
	at com.alipay.sofa.ark.container.service.biz.BizCommandProvider$BizCommand$1.run(BizCommandProvider.java:249)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lvjing2** [comment]
框架类与中间件类都委托，这是最佳实践
